Bearer Token Auth via kubernetes Apiserver (#445)
* apiserver work

* updated glide yaml/lock

* update vendor to match the new glide values

* Create and return genericapiserver from ApiServer method

* more stupid changes
* broker runs but does not stay up.

* add natefinch dep

* getting genericapiserver working.

* making the initialization a little cleaner.

* No support for insecure.
* if no certs given will generate its own
* ignor the folder that the certs get generated too

* Working deploy template and apiserver

* addressing pr comments.

* Still trying to remove insecure broker code.

* Adding ability for basic auth to override the bearer token auth.

* template and catasb are still defaulting for bearer token auth.

* adding temporary template to be used for a couple of days

* fixing gate build for a couple of days

* Adding ability to serve at the root url

* getting gate build working

* fixing build. going back to a single deployment template

diff --git a/vendor/github.com/containers/image/Makefile b/vendor/github.com/containers/image/Makefile
--- a/vendor/github.com/containers/image/Makefile
+++ b/vendor/github.com/containers/image/Makefile
@@ -1,22 +1,45 @@
-.PHONY: all deps test validate lint
+.PHONY: all tools test validate lint
 
 # Which github repostiory and branch to use for testing with skopeo
 SKOPEO_REPO = projectatomic/skopeo
 SKOPEO_BRANCH = master
 # Set SUDO=sudo to run container integration tests using sudo.
 SUDO =
-BUILDTAGS   = btrfs_noversion libdm_no_deferred_remove
+
+ifeq ($(shell uname),Darwin)
+DARWIN_BUILD_TAG = containers_image_ostree_stub
+endif
+BUILDTAGS = btrfs_noversion libdm_no_deferred_remove $(DARWIN_BUILD_TAG)
 BUILDFLAGS := -tags "$(BUILDTAGS)"
 
-all: deps .gitvalidation test validate
+PACKAGES := $(shell go list $(BUILDFLAGS) ./... | grep -v github.com/containers/image/vendor)
+# On macOS, (brew install gpgme) installs it within /usr/local, but /usr/local/include is not in the default search path.
+# Rather than hard-code this directory, use gpgme-config. Sadly that must be done at the top-level user
+# instead of locally in the gpgme subpackage, because cgo supports only pkg-config, not general shell scripts,
+# and gpgme does not install a pkg-config file.
+# If gpgme is not installed or gpgme-config can’t be found for other reasons, the error is silently ignored
+# (and the user will probably find out because the cgo compilation will fail).
+GPGME_ENV = CGO_CFLAGS="$(shell gpgme-config --cflags 2>/dev/null)" CGO_LDFLAGS="$(shell gpgme-config --libs 2>/dev/null)"
 
-deps:
-	go get -t $(BUILDFLAGS) ./...
-	go get -u $(BUILDFLAGS) github.com/golang/lint/golint
-	go get $(BUILDFLAGS) github.com/vbatts/git-validation
+all: tools .gitvalidation test validate
 
-test:
-	@go test $(BUILDFLAGS) -cover ./...
+tools: tools.timestamp
+
+tools.timestamp: Makefile
+	@go get -u $(BUILDFLAGS) github.com/golang/lint/golint
+	@go get $(BUILDFLAGS) github.com/vbatts/git-validation
+	@go get -u github.com/rancher/trash
+	@touch tools.timestamp
+
+vendor: tools.timestamp vendor.conf
+	@trash
+	@touch vendor
+
+clean:
+	rm -rf vendor tools.timestamp
+
+test: vendor
+	@$(GPGME_ENV) go test $(BUILDFLAGS) -cover $(PACKAGES)
 
 # This is not run as part of (make all), but Travis CI does run this.
 # Demonstarting a working version of skopeo (possibly with modified SKOPEO_REPO/SKOPEO_BRANCH, e.g.
@@ -29,19 +52,19 @@ test-skopeo:
 		skopeo_path=$${GOPATH}/src/github.com/projectatomic/skopeo && \
 		vendor_path=$${skopeo_path}/vendor/github.com/containers/image && \
 		git clone -b $(SKOPEO_BRANCH) https://github.com/$(SKOPEO_REPO) $${skopeo_path} && \
-		rm -rf $${vendor_path} && cp -r . $${vendor_path} && \
+		rm -rf $${vendor_path} && cp -r . $${vendor_path} && rm -rf $${vendor_path}/vendor && \
 		cd $${skopeo_path} && \
 		make BUILDTAGS="$(BUILDTAGS)" binary-local test-all-local && \
-		$(SUDO) make check && \
+		$(SUDO) make BUILDTAGS="$(BUILDTAGS)" check && \
 		rm -rf $${skopeo_path}
 
 validate: lint
-	@go vet ./...
-	@test -z "$$(gofmt -s -l . | tee /dev/stderr)"
+	@go vet $(PACKAGES)
+	@test -z "$$(gofmt -s -l . | grep -ve '^vendor' | tee /dev/stderr)"
 
 lint:
-	@out="$$(golint ./...)"; \
-	if [ -n "$$(golint ./...)" ]; then \
+	@out="$$(golint $(PACKAGES))"; \
+	if [ -n "$$out" ]; then \
 		echo "$$out"; \
 		exit 1; \
 	fi
@@ -52,9 +75,9 @@ EPOCH_TEST_COMMIT ?= e68e0e1110e64f906f9b482e548f17d73e02e6b1
 
 # When this is running in travis, it will only check the travis commit range
 .gitvalidation:
-	@which git-validation > /dev/null 2>/dev/null || (echo "ERROR: git-validation not found. Consider 'make deps' target" && false)
+	@which git-validation > /dev/null 2>/dev/null || (echo "ERROR: git-validation not found. Consider 'make clean && make tools'" && false)
 ifeq ($(TRAVIS),true)
-	@git-validation -q -run DCO,short-subject,dangling-whitespace
+	git-validation -q -run DCO,short-subject,dangling-whitespace
 else
-	@git-validation -q -run DCO,short-subject,dangling-whitespace -range $(EPOCH_TEST_COMMIT)..HEAD
+	git-validation -q -run DCO,short-subject,dangling-whitespace -range $(EPOCH_TEST_COMMIT)..HEAD
 endif
